
DROP DATABASE IF EXISTS `wolfpack`;

USE wolfpack;

DROP TABLE IF EXISTS `Users`;

CREATE TABLE `Users` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT DEFAULT NULL,
  `Username` VARCHAR(20) NOT NULL DEFAULT 'NULL',
  `Password` VARCHAR NOT NULL DEFAULT 'NULL',
  PRIMARY KEY (`ID`)
);

DROP TABLE IF EXISTS `Listings`;

CREATE TABLE `Listings` (
  `ID` INTEGER NOT NULL AUTO_INCREMENT DEFAULT NULL,
  `Initializer` INT NOT NULL DEFAULT NULL,
  `Price` INTEGER NOT NULL DEFAULT NULL,
  `Complete` INTEGER NOT NULL DEFAULT 0,
  `Location` MEDIUMTEXT NOT NULL DEFAULT 'NULL',
  `Num_of_participants` INTEGER NOT NULL DEFAULT NULL,
  PRIMARY KEY (`Initializer`)
);

DROP TABLE IF EXISTS `User Listings`;

CREATE TABLE `User Listings` (
  `User_ID` INTEGER NOT NULL DEFAULT NULL,
  `Listing_ID` INTEGER NOT NULL DEFAULT NULL,
  `Received` INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (`User_ID`)
);
